canonical/ubuntu-openstack-rocks

- rocks/horizon/python/plugin_management.py
- rocks/horizon/rockcraft.yaml
Horizon plugins are python files that must be placed in specific location.
This change is adding facilities to enable easy plugin management from the charm.
Adding the script `plugin_management.py`, with the following usage:
```
Usage: plugin_management.py <command> <plugin>...
Commands: enable, disable
```
Example:
```
/usr/bin/plugin_management.py enable magnum
Enabled '_1370_project_container_infra_panel_group.py'
Enabled '_1371_project_container_infra_clusters_panel.py'
Enabled '_1372_project_container_infra_cluster_templates_panel.py'
Enabled '_2370_admin_container_infra_panel_group.py'
Enabled '_2371_admin_container_infra_quotas_panel.py'
```
The plugin will lookup the file
`/usr/lib/python3/dist-packages/openstack_dashboard/available/<plugin name>`. If this file is missing, aborts. …
> Add plugin management capabilities to horizon

- rocks/magnum-api/rockcraft.yaml
- rocks/magnum-conductor/rockcraft.yaml
- rocks/magnum-consolidated/rockcraft.yaml
Bug [1] between magnum and barbican has been fixed in magnum 16.0.1 which is currently served in proposed pocket.
[1]: https://storyboard.openstack.org/#!/story/2010629
> Switch magnum to proposed pocket from UCA

- rocks/horizon/rockcraft.yaml
Heat and Magnum packages share files but with different permission. This is not allowed in different Rockcraft parts. Merge all the parts to fix the issue, and simplify the Rockcraft file.
> Refactor horizon plugins + add heat

- .github/workflows/push.yaml
If any change is made to stable/2023.1, github should automatically publish the changes.
> Enable publishing on pushing to stable

- .github/workflows/publish_branch.yaml
publish_branch workflow build-and-publish step
retrieves incorrect value for rock name.
Step rockcraft outputs rock file path from running directory instead of just rock filename. So modify retrieving rockname logic by using cut.
> Fix retrieving rock name in publish_branch workflow

- .github/workflows/build_publish.yaml
- .github/workflows/publish_branch.yaml
This ensures the workflow works with any branch rather than just the main branch.
> publich-brnach: pass branch to publish-rock

- rocks/horizon/rockcraft.yaml
Memcache library dependency was removed in bobcat, adding it back in because to keep old behavior (failing silently) while it's fixed.
> Install python3-memcache library in horizon

- .github/workflows/pull_request.yaml
Since branch was passed to the build-and-publish workflow, the input branch was made optional with default "main".
In case of a pull request, we want the workflow to run on the PR's branch, and not main.
> Use trigger ref when building rocks on pull request

- rocks/tempest/LICENSE
- rocks/tempest/README.md
- rocks/tempest/rockcraft.yaml
Implement tempest snap as a rock image for tempest-k8s operator
> Add Tempest rock

- .github/workflows/push.yaml
Since the branch possibility update, another branch than main was not possible in push workflow; Add branch ref.
> Allow push on other branch than main

- rocks/tempest/rockcraft.yaml
To address errors downloading cirros image by discover-tempest-config
```
unit-tempest-0: 15:27:26 ERROR unit.tempest/0.juju-log     2024-02-13 04:57:02.346 22 INFO config_tempest.constants [-] Creating image 'cirros-0.5.2-x86_64-disk.img'
unit-tempest-0: 15:27:26 ERROR unit.tempest/0.juju-log     2024-02-13 04:57:02.346 22 INFO config_tempest.constants [-] Downloading 'https://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img' and saving as '/var/lib/tempest/etc/cirros-0.5.2-x86_64-disk.img'
unit-tempest-0: 15:27:26 ERROR unit.tempest/0.juju-log     2024-02-13 04:57:03.030 22 WARNING config_tempest.constants [-] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>, Retrying in 3 seconds.: …
```
> Add ca-certificates to tempest rock

- rocks/tempest/rockcraft.yaml
Backport https://github.com/canonical/ubuntu-openstack-rocks/pull/34
> [2023.1 backport] Add ca-certificates to tempest rock

- rocks/horizon/rockcraft.yaml
Rockcraft's scriptlet runner is checking final exit code. Since we were using negative tests, the final exit code was 1 (even though there were no errors). Flip the conditions so that they return 0 when there's no issue.
> Flip plugin files condition

- rocks/aodh-evaluator/rockcraft.yaml
- rocks/aodh-expirer/rockcraft.yaml
- rocks/aodh-listener/rockcraft.yaml
- rocks/aodh-notifier/rockcraft.yaml
- rocks/barbican-worker/rockcraft.yaml
- rocks/ceilometer-central/rockcraft.yaml
- rocks/ceilometer-notification/rockcraft.yaml
- rocks/cinder-scheduler/rockcraft.yaml
- rocks/cinder-volume/rockcraft.yaml
- rocks/designate-central/rockcraft.yaml
- rocks/designate-mdns/rockcraft.yaml
- rocks/designate-producer/rockcraft.yaml
- rocks/designate-worker/rockcraft.yaml
- rocks/glance-api/rockcraft.yaml
- rocks/gnocchi-metricd/rockcraft.yaml
- rocks/heat-engine/rockcraft.yaml
- rocks/magnum-conductor/rockcraft.yaml
- rocks/neutron-server/rockcraft.yaml
- rocks/nova-conductor/rockcraft.yaml
- rocks/nova-scheduler/rockcraft.yaml
- rocks/octavia-driver-agent/rockcraft.yaml
- rocks/octavia-housekeeping/rockcraft.yaml
Add user and group to service definitions
for openstack services other than apache
> Add user/group to service definitions

- rocks/openstack-images-sync/rockcraft.yaml
Latest version included: https://github.com/canonical/openstack-images-sync/pull/2
Feature needed not to remove in-use images
> Update openstack images sync to latest version

- rocks/openstack-exporter/README.md
- rocks/openstack-exporter/rockcraft.yaml
With the move to juju 3.5, the pebble daemon is started with uid/gid of the user `_daemon_`. This fails in the charm since it's trying to create files where it does not have rights to. Pre-create them in the rock.
> Create configuration folder as _daemon_ owned

- .github/actions/publish-rock/action.yaml
Main archive's skopeo is much more recent than the snap.
> Use skopeo from main archive

- .github/actions/publish-rock/action.yaml
Don't pass by intermediate docker daemon to publish the OCI image.
> Publish directly to ghcr registry

- rocks/openstack-exporter/rockcraft.yaml
OpenStack-exporter has been improved to cache the metrics not to timeout on prometheus scrape.
> Upgrade openstack-exporter to pull cache feature

- .github/workflows/build_publish.yaml
Commit b7a328ad518d91ae9b19c4e7ee264bbbe696befd pins lxd to 5.21/candidate to avoid mounting issues.
The issue is fixed now and released in 5.21/stable
Pin lxd to 5.21/stable.
rockcraft-pack main does not refresh the lxd if it already exists.
Pin rockcraft-pack to main.
> [github workflow] Pin lxd to 5.21/stable

- rocks/horizon/rockcraft.yaml
Summary of changes:
- Add masakari-dashboard package to horizon
- Adjust override-prime script to find masakari-dashboard file which writes to /local/enabled rather then /enabled like the others
> Add masakari-dashboard to horizon

- rocks/magnum-api/rockcraft.yaml
- rocks/magnum-conductor/rockcraft.yaml
- rocks/magnum-consolidated/rockcraft.yaml
- rocks/watcher-api/rockcraft.yaml
- rocks/watcher-applier/rockcraft.yaml
- rocks/watcher-consolidated/rockcraft.yaml
- rocks/watcher-decision-engine/rockcraft.yaml
Magnum and Watcher exhibit python3.12 compatibility issues which are not planned to be fixed before 2025.1, downgrade back to ubuntu@22.04 to run python3.10.
> Downgrade watcher and magnum to 22 base

- rocks/tempest/rockcraft.yaml
Use tempest snap 2024.1/stable.
Tempest 41.x will be deployed.
> [tempest] Use tempest snap 2024.1/stable

- rocks/tempest/rockcraft.yaml
Tempest's snap `latest/candidate` contains 43.0.0, epoxy release.
> Update tempest to epoxy

- cookiecutter_code/rock/{{cookiecutter.rock_name}}/rockcraft.yaml
- tox.ini
When generating new rocks through cookiecutter, a few errors can occur:
- If the requirements are not met (`virtualenv < 20.0`), a new environment will be created, however, that will eventually fail with the following error: `ModuleNotFoundError: No module named 'distutils'`. Note that `distutils` has been removed in Python 3.12 [1].
- `/bin/true` is not in the tox `allowlist_externals`, resulting in this error: `failed with /bin/true (resolves to /bin/true) is not allowed, use allowlist_externals to allow it`.
- all other rocks are using the `proposed` pocket, the cookiecutter should too.
[1] https://docs.python.org/3/whatsnew/3.12.html#summary-release-highlights
> Minor fixes for cookiecutter rock generation

- rocks/keystone/rockcraft.yaml
The libapache2-mod-oauth2 module is needed when implementing a multi openid IDP setup, in conjunction with AuthType auth-openidc. That flow does not properly fetch the verification keys for JWT token validation from the jwks_uri. We can work around this limitation by using the OAuth2TokenVerify option from mod-oauth2.
The openid-connect auth type does not have this limitation.
> Add libapache2-mod-oauth2 to keystone

- rocks/horizon/rockcraft.yaml
Adds the necessary package and files for enabling the manila horizon plugin.
Additionally, prevents the plugins from being enabled by default by moving the already primed files from enabled to available.
(cherry picked from commit e2f2bf467f7f0a1e71cb8f64b7bb1ef3f997f409)
> Adds horizon manila plugin

- rocks/openstack-images-sync/rockcraft.yaml
ports.conf has the default configuration instead of empty file. This breaks http-sync since the service is also trying to run on port 80 which is already
defined in ports.conf
Remove ports.conf as part of overlay-script
> [openstack-images-sync] Remove ports.conf in overlay

- rocks/ironic-conductor/LICENSE
- rocks/ironic-conductor/README.md
- rocks/ironic-conductor/rockcraft.yaml
The rock contains the `ironic-conductor`, `apache2`, and `tftpd-hpa` packages.
> Adds ironic-conductor rock

- rocks/ironic-consolidated/rockcraft.yaml
- rocks/ironic-novncproxy/rockcraft.yaml
The package is required by `ironic-novncproxy`.
> ironic: Adds novnc package to ironic-novncproxy and ironic-consolidated
